# Generated by Django 3.2.9 on 2022-10-18 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe_Addtional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseball', models.BooleanField(default=False)),
                ('cycling', models.BooleanField(default=False)),
                ('boxing', models.BooleanField(default=False)),
                ('beach', models.BooleanField(default=False)),
                ('basketball', models.BooleanField(default=False)),
                ('bodybuliding', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_time']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='item_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fee',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('condition', models.CharField(choices=[('new with tag', 'New with tag'), ('new but has defects', 'New but has defects'), ('thrift', 'Thrift')], default='None', max_length=20)),
                ('release_year', models.DateField()),
                ('shoe_size', models.FloatField()),
                ('customized', models.BooleanField(default=False)),
                ('shilhouette', models.CharField(blank=True, max_length=50, null=True)),
                ('country_manufacture', models.CharField(max_length=20)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('item_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('team', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('item_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='item_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location'),
        ),
    ]
