# Generated by Django 3.2.9 on 2022-08-16 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('suna', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('swiming_pool', models.BooleanField(default=False)),
                ('working_space', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('water_pump', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_option', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=100)),
                ('bed_rooms', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('salon', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('condo', 'Condominum'), ('apt', 'Apertment'), ('store', 'Store'), ('land', 'Land'), ('office', 'Office')], default=None, max_length=200)),
                ('desc', models.TextField(default='description')),
                ('area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=30)),
                ('property_title', models.CharField(max_length=120)),
                ('listing_status', models.CharField(choices=[('sold', 'Sold'), ('active', 'Active')], default='active', max_length=10)),
                ('imageF', models.ImageField(blank=True, upload_to='home/')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_feat', to='listing.house_feat')),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.leads')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_location', to='listing.location')),
                ('tour', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='listing.requesttour')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home/')),
                ('listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='listing.propertylisting')),
            ],
        ),
    ]
