# Generated by Django 3.2.9 on 2022-08-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_propertylisting_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='tour',
        ),
        migrations.AddField(
            model_name='leads',
            name='listings',
            field=models.ForeignKey(default=142, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listing.propertylisting'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RequestTour',
        ),
    ]
