# Generated by Django 3.2.9 on 2022-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20220821_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
