# Generated by Django 3.2.9 on 2022-08-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_reqtour'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='tour',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.reqtour'),
            preserve_default=False,
        ),
    ]
