# Generated by Django 3.2.9 on 2022-08-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_propertylisting_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='tour',
        ),
    ]
