# Generated by Django 3.2.9 on 2022-08-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_remove_propertylisting_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='tours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.reqtour'),
            preserve_default=False,
        ),
    ]
