# Generated by Django 3.2.9 on 2022-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_propertylisting_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
