# Generated by Django 3.2.9 on 2022-08-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
