# Generated by Django 3.2.9 on 2022-09-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_propertylisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
