# Generated by Django 3.2.9 on 2022-09-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_propertylisting_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='usr',
        ),
    ]
