# Generated by Django 3.2.9 on 2022-09-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_propertylisting_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='owner',
        ),
    ]
