# Generated by Django 3.2.9 on 2022-09-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='listing.propertylisting'),
        ),
    ]
