# Generated by Django 3.2.9 on 2022-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_auto_20221001_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
