# Generated by Django 3.2.9 on 2022-10-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_propertylisting_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylisting',
            old_name='slug',
            new_name='slugg',
        ),
    ]
