# Generated by Django 3.2.9 on 2022-10-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_rename_slug_propertylisting_slugg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='slugg',
        ),
    ]
