# Generated by Django 3.2.9 on 2022-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_remove_propertylisting_slugg'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
