# Generated by Django 3.2.9 on 2022-10-20 20:22

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cloth_Fiber_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotton', models.BooleanField(default=False)),
                ('linen', models.BooleanField(default=False)),
                ('synthetic', models.BooleanField(default=False)),
                ('silk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe_Addtional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseball', models.BooleanField(default=False)),
                ('cycling', models.BooleanField(default=False)),
                ('boxing', models.BooleanField(default=False)),
                ('beach', models.BooleanField(default=False)),
                ('basketball', models.BooleanField(default=False)),
                ('bodybuliding', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('condition', models.CharField(choices=[('new with tag', 'New with tag'), ('new but has defects', 'New but has defects'), ('thrift', 'Thrift')], default='None', max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('release_year', models.DateField()),
                ('shoe_size', models.FloatField()),
                ('customized', models.BooleanField(default=False)),
                ('shilhouette', models.CharField(blank=True, max_length=50, null=True)),
                ('country_manufacture', models.CharField(blank=True, max_length=20, null=True)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('item_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('item_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('price', models.FloatField()),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('item_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('handmade', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=40)),
                ('condition', models.CharField(choices=[('new with tag', 'New with tag'), ('new but has defects', 'New but has defects'), ('thrift', 'Thrift')], default='None', max_length=20)),
                ('country_manufacture', models.CharField(max_length=20)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('cloth_fiber_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cloth_fiber_content')),
                ('item_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('item_desc', models.TextField()),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
                ('artist', models.CharField(max_length=40)),
                ('style', models.CharField(max_length=40)),
                ('material', models.CharField(max_length=40)),
                ('year_production', models.DateField()),
                ('paint_color', models.CharField(max_length=30)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=50, null=True)),
                ('rarity', models.CharField(choices=[('unique', 'Unique'), ('limited edition', 'Limit edition'), ('unknown edition', 'Unkown edition')], default='None', max_length=40)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('item_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
    ]
