# Generated by Django 3.2.9 on 2022-10-20 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('none', 'None'), ('abisynia', 'Abisynia'), ('cbe', 'CBE')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_recipt', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('create_time', models.DateField()),
                ('description', models.TextField()),
                ('plan_name', models.CharField(choices=[('free', 'Free'), ('sliver', 'Sliver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=14)),
                ('tax', models.FloatField()),
                ('price', models.FloatField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('admin', 'ADMIN'), ('stuff', 'STUFF'), ('seller', 'SELLER'), ('user', 'USER')], default='user', max_length=150)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile/')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('credit_balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(choices=[('FREE', 'free'), ('PAID', 'paid')], default='free', max_length=60)),
                ('payment_status', models.CharField(choices=[('PENDING', 'pending'), ('FAILED', 'failed'), ('PAID', 'paid'), ('NONE', 'none')], default='none', max_length=80)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
