# Generated by Django 3.2.9 on 2022-07-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedual', '0002_album_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
