# Generated by Django 3.2.9 on 2022-10-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('stuff', 'STUFF'), ('seller', 'SELLER'), ('user', 'USER')], default='user', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(choices=[('cbe', 'CBE'), ('awash', 'AWASH'), ('abysiniya', 'ABYSINIYA')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acc.subscription'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_name',
            field=models.CharField(choices=[('none', 'None'), ('abisynia', 'Abisynia'), ('cbe', 'CBE')], max_length=20, null=True),
        ),
    ]
