# Generated by Django 3.2.9 on 2022-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20221006_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
