# Generated by Django 3.2.9 on 2022-10-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20221011_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
