# Generated by Django 3.2.9 on 2022-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20221011_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
