# Generated by Django 3.2.9 on 2022-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_balance',
            field=models.FloatField(default=0),
        ),
    ]
