# Generated by Django 3.2.9 on 2022-10-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_alter_profile_credit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription',
        ),
    ]
